name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}-news-backend
  PY_VERSION: "3.13"

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx feedparser
      - name: Run backend tests
        run: |
          export PYTHONPATH=$PYTHONPATH:./backend
          pytest tests -q
  frontend-tests:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install & start http-server
        run: |
          npm install http-server
          npx http-server frontend -p 8001 &
          sleep 2
          curl -f http://localhost:8001/index.html
  docker-login:
    name: "Docker: логін до Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "Username is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "Password is set: ${{ secrets.DOCKER_PASSWORD != '' }}"



      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
